### ISSUE TITLE
Chicken and egg?

### ISSUE THREAD

**Issue by Phando** [Lerc/canvas_tab#1]
Thank you for the canvas node. I am trying to use your workflow and am getting an error. The ImageCompositeMasked is complaining that there is no image. How did you get the onioin in your canvas node? Not sure where to start with your workflow to duplicate your example.

**Comment by Lerc** [comment]
I drew a rough scribble version of the image in the editor and set the mask to cover the scribble to start things off. 

I can see that it probably doesn't send the image through until you draw something,  I'll add something to do a default.

**Comment by Lerc** [comment]
I made some slight changes to the editor to auto-launch if it is not open when you send it an image, and provided a simple testcase workflow.  

![](https://raw.githubusercontent.com/Lerc/canvas_tab/main/Canvas_tab_basic.png)

**Comment by Phando** [comment]
Thank you for the update. The new workflow works, but I really wanted to get your inpainting example working. Quick identification of an area that needs inpainting is kinda magical. 

![Screenshot 2023-09-28 at 3 42 59 PM](https://github.com/Lerc/canvas_tab/assets/215984/58236308-a2ec-4d7c-871f-ecc08b548574)
