### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by otterslide** [Lerc/canvas_tab#2]
I downloaded the module, added it to custom_nodes, then added the node, and click "Edit".
It launches "http://127.0.0.1:8188/extensions/canvas_tab/page/index.html" which gives "404: Not Found"
any idea what I'm doing wrong?
Thanks.

**Comment by otterslide** [comment]
I got it working by copying the module to "ComfyUI/web/extensions/canvas_tab" as well.. I have it both in custom_nodes and in web/extensions.  Was this the proper way to install it?

**Comment by Lerc** [comment]
Ah,  I should update the instructions,  I took out the bit that auto set that up when I changed it to be installed by comfy manager.   If you install with comfy manager this step won't be necessary.   https://github.com/ltdrdata/ComfyUI-Manager

**Comment by FreezaSama** [comment]
Humm same happened to me just now out of the blue... the node shows up but cannot draw. the repository was reinstalled under web/extensions/canvas_tab ... still nothing. any ideas on how to bring it back up?

**Comment by Lerc** [comment]
It does that. 
https://github.com/Lerc/canvas_tab/blob/a3a7d03444cc604e78caf76d186a6ab99573e156/__init__.py#L135

 I thought that was a property of comfy manager.    Does ComfyUI itself handle WEB_DIRECTORY?

**Comment by Lerc** [comment]
OK, updated documentation to reflect that.
