### ISSUE TITLE
The Canvas Tab has interface scale issues at lower resolutions.

### ISSUE THREAD

**Issue by Ferniclestix** [Lerc/canvas_tab#8]
Running this on a 1366X768 monitor breaks the interface in two places.
1- the color swatches go out of position and do not register as the displayed colors.
2- when a scroll bar appears because of the stretching interface zooming in and out becomes unreliable and confusing at best.

Now, its not an issue for me, I can use another monitor but this is going to be an issue for anyone with smaller laptops or runnning SD over a local network on netbooks, phones, or other kinds of computers which is more common than you would think.

edit- running on OperaGX

-Love the node by the way, fantastic job, even made a tutorial about using it. 
https://youtu.be/DROM8vfIYUY  :D

**Comment by Lerc** [comment]
Added something to scale down to 0.75 when on a smaller screen
