### ISSUE TITLE
REQUEST: update triggers Queue Prompt?

### ISSUE THREAD

**Issue by Duemellon** [Lerc/canvas_tab#9]
Is there a way you can create a node or a switch that will prompt/launch the queue to run when the canvas image is updated?

That would truly make it as close to "real time" as possible.

**Comment by Lerc** [comment]
In the works.  I have it running on my machine.  Possibly push it tomorrow if nothing breaks.

**Comment by Lerc** [comment]
A toggle has been added to enable this.

**Comment by NicolasCampailla** [comment]
Where is the toggle?

**Comment by Lerc** [comment]
Sorry,  forgot to push again.  should be there now.
